const hre = require("hardhat");

async function main() {
  const KERIAnchor = await hre.ethers.getContractFactory("KERIAnchor");
  const keriAnchor = await KERIAnchor.deploy();

  await keriAnchor.waitForDeployment();
  const address = await keriAnchor.getAddress();

  console.log(`🛡️  Zero-Trust Anchor deployed to: ${address}`);

  // --- AUTOMATIC AUTHORIZATION FOR DEMO ---
  // Replace this string with the actual AID generated by your gateway.py
  // You can find it in the gateway logs: "Created KERI Identity (AID): ..."
  const GATEWAY_AID = "ELDgfHZfXoYYL5546qIUETlxdh1Wxgtd6ooDltB3xspa"; 
  
  console.log(`🔐 Authorizing Gateway: ${GATEWAY_AID}...`);
  const tx = await keriAnchor.authorizeDevice(GATEWAY_AID);
  await tx.wait();
  console.log("✅ Gateway Authorized.");
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});